# Generated by Django 4.1.1 on 2026-03-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0006_userregisteredtable_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisteredtable',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='userregisteredtable',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='userregisteredtable',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='userregisteredtable',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
