# Generated by Django 4.1.1 on 2026-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0007_remove_userregisteredtable_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle1',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
