# Generated by Django 4.1.1 on 2026-03-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0008_vehicle1_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle1',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
