# Generated by Django 4.1.1 on 2026-03-18 08:06

from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_vehicle_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTODatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True, validators=[seller.models.validate_vehicle_number])),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
