# Generated by Django 4.1.1 on 2026-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_vehicle_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
