# Generated by Django 4.1.1 on 2026-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_rtodatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtodatabase',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
