# Generated by Django 4.1.1 on 2026-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_alter_rtodatabase_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregisteredtable',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
