# Generated by Django 4.1.1 on 2026-04-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_vehicle_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregisteredtable',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
