# Generated by Django 4.1.1 on 2026-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_sellerregisteredtable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregisteredtable',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
