# Generated by Django 4.1.1 on 2026-04-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_sellerregisteredtable_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('other', 'Other')], default='car', max_length=20),
        ),
    ]
